### ISSUE TITLE
Use story.internalId

### ISSUE THREAD

**Issue by raae** [schabibi1/stackblitz-gatsby-source-storyblok#13]
When sourcing nodes an `internalId`  is set, it's set to the original storyblok id. I think it would be beneficial to use this `internalId` as the source of truth for the storyblok id. The content node (gatsby) id implementation might change, and probably should be changed to use `createNodeId`.

It sets for both DefaultNodes:
https://github.com/schabibi1/stackblitz-gatsby-source-storyblok/blob/55b10112b3df1b7a5fa9e59e900363cdc593e1a7/lib/src/sync.js#L49
and DatasourceEntryNode:
https://github.com/schabibi1/stackblitz-gatsby-source-storyblok/blob/55b10112b3df1b7a5fa9e59e900363cdc593e1a7/lib/src/sync.js#L63

`story.id` here would then change to `story.internalId`:
https://github.com/schabibi1/stackblitz-gatsby-source-storyblok/blob/55b10112b3df1b7a5fa9e59e900363cdc593e1a7/playground/src/lib/storyblok.js#L15

It depends on `internalId` being queried and available in the page query etc:
https://github.com/schabibi1/stackblitz-gatsby-source-storyblok/blob/55b10112b3df1b7a5fa9e59e900363cdc593e1a7/playground/src/pages/index.js#L56

**Comment by raae** [comment]
Yes, whatever you use as the argument should be unique inside of the Storyblok universe and Gatsby makes sure it is unique in the Gatsby universe. So you might not need name in there.

**Comment by raae** [comment]
You might also want to look at createContentDigest. I [wrote about it today](https://queen.raae.codes/emails/2022-05-03-content-digest/). PS: not in reference to Storyblok actually, it's been on the email idea block for a while. I even see it in Gatsby docs sometimes.

**Comment by schabibi1** [comment]
Hey @raae 
`name` might be still needed as we're conditionally looking at the value `StoryblokDatasourceEntry` from `lib/src/sync.js` and `lib/gatsby-node.js`

https://github.com/schabibi1/stackblitz-gatsby-source-storyblok/blob/735cb10bb57c4ba499d91d5c01e6fe691d0a7839/lib/src/sync.js#L36-L39

https://github.com/schabibi1/stackblitz-gatsby-source-storyblok/blob/735cb10bb57c4ba499d91d5c01e6fe691d0a7839/lib/gatsby-node.js#L74

https://github.com/schabibi1/stackblitz-gatsby-source-storyblok/blob/735cb10bb57c4ba499d91d5c01e6fe691d0a7839/lib/gatsby-node.js#L88

Thanks for the tips and your article is very useful information!
I can see some potential refactoring in this plugin. Might pin you for upcoming questions!
